name: hypad
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cudatoolkit=11.3.1
  - cudnn=8.2.1.32
  - freetype=2.12.1
  - future=0.18.3
  - giflib=5.2.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libpng=1.6.39
  - libprotobuf=3.18.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - magma=2.5.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nccl=2.12.12.1
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=1.1.1t
  - pandas=1.5.3
  - pip=23.0.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.9.1
  - pytorch-gpu=1.9.1
  - pytz=2022.7
  - pyyaml=6.0
  - readline=8.2
  - requests=2.29.0
  - setuptools=66.0.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.41.2
  - tk=8.6.12
  - torchaudio=0.9.1
  - torchvision=0.10.1
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cmake==3.26.3
      - combo==0.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - filelock==3.12.0
      - fonttools==4.39.3
      - geoopt==0.5.0
      - importlib-resources==5.12.0
      - jinja2==3.1.2
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - lit==16.0.2
      - llvmlite==0.40.0
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - mpmath==1.3.0
      - networkx==3.1
      - numba==0.57.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - packaging==23.1
      - pillow==9.5.0
      - pyod==1.0.9
      - pyparsing==3.0.9
      - pyts==0.12.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - sympy==1.11.1
      - threadpoolctl==3.1.0
      - torch==1.9.0
      - triton==2.0.0
      - zipp==3.15.0
